services:
  herbarium:
    container_name: herbarium
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    env_file:
      - .env

  varnish:
    image: varnish
    container_name: herbarium-varnish
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    environment:
      VARNISH_SIZE: 256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - herbarium
