services:
  herbarium:
    container_name: herbarium
    tmpfs:
      - /var/lib/varnish:rw,size=1g,exec
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  herbarium_database:
    image: postgres:18
    container_name: herbarium_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-herbarium}
      POSTGRES_USER: ${POSTGRES_USER:-herbarium}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - herbarium_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  herbarium_data:
